/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test_MyInterface */

#ifndef _Included_Test_MyInterface
#define _Included_Test_MyInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
